UiCustomStyle = {
    customLayers = {
        bgButton = sprites.bgButton,
        -- bgSlider = bgSlider,
        -- bgSliderVertical = bgSliderVertical,
        -- bgText = bgText,
        -- bgProgressbar = bgProgressbar,
        -- fgProgressbar = fgProgressbar,
        -- bgMulti = bgMulti,
        -- bgToggle = bgToggle,
        -- fgSlider = fgSlider,
        -- fgSliderOn = fgSliderOn,
        -- fgSliderVertical = fgSliderVertical,
        -- fgSliderVerticalOn = fgSliderVerticalOn,
        -- fgToggle = fgToggle,
        -- fgToggleOn = fgToggleOn,
    },
    -- progressBarGooColor = { 0, 1, 0, 0.7 },
    cornerRadius = 0,
    fgColor = { love.math.colorFromBytes(255, 255, 255) },
    hoverFgColor = { love.math.colorFromBytes(75, 114, 110) },
    pressedFgColor = { love.math.colorFromBytes(140, 171, 161) },
    disableFgColor = { 0.2, 0.2, 0.2 },
}
