function requireAll()
    _G.urutora = require('lib/urutora/urutora')
    require("src/startup/collisionClasses")

    -- Load assets, resources, data
    require("src/startup/resources")
    require("src/utilities/class")
    require("src/mechanics/ComboManager")
    require("src/startup/GameState")
    require("src/startup/data")
    require("src/utilities/camera")
    require("src/utilities/destroyAll")
    require("src/utilities/LoveGraphicsUtil")
    _G.util = require("src/utilities/util")
    require("../PolygonMasker/PolygonMask")
    require("src/actors/player")
    require("src/effects/MergeEffect")
    require("src/skills/FruitThrow")
    require("src/FruitTypes")
    require("src/fruit")
    require("src.ui.components.FruitEvoWheel")
    require("src.ui.components.WarningBar")
    require("src/Limiter")
    require("src/ui/Style")
    require("src/ui/Fonts")
    require("src/ui/GameInterface")
    require("src/ui/GameOverMenu")
    require("src/ui/MainMenu")
    require("src/cutscenes/Cutscene")
    require("src/cutscenes/LogoCutsceneSeq")
    require("src/cutscenes/GameOverCutsceneSeq")
    _G.update = require("src/update")
    _G.draw = require("src/draw")
    require("src/levels/loadMap")
end
